### ISSUE TITLE
Dotori 다운이유 로그가 생겼다. 야호.

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#267]
```
2020/02/18 07:41:15 request Content-Type isn't multipart/form-data
2020/02/18 07:41:15 http: panic serving 46.229.168.152:39370: runtime error: invalid memory address or nil pointer dereference
goroutine 1449 [running]:
net/http.(*conn).serve.func1(0xc0003fc140)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1769 +0x139
panic(0x1450ec0, 0x1912190)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
main.handleUploadMaya(0x161c4e0, 0xc000364000, 0xc0002bc800)
	/Users/woong/dotori/http_add.go:120 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1597dd0, 0x161c4e0, 0xc000364000, 0xc0002bc800)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1921b40, 0x161c4e0, 0xc000364000, 0xc0002bc800)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000109380, 0x161c4e0, 0xc000364000, 0xc0002bc800)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0003fc140, 0x161cde0, 0xc00002eb40)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2884 +0x2f4
2020/02/18 07:41:15 request Content-Type isn't multipart/form-data
2020/02/18 07:41:15 http: panic serving 46.229.168.152:55508: runtime error: invalid memory address or nil pointer dereference
goroutine 1477 [running]:
net/http.(*conn).serve.func1(0xc00046e000)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1769 +0x139
panic(0x1450ec0, 0x1912190)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
main.handleUploadMaya(0x161c4e0, 0xc0002ea000, 0xc0002bd300)
	/Users/woong/dotori/http_add.go:120 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1597dd0, 0x161c4e0, 0xc0002ea000, 0xc0002bd300)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1921b40, 0x161c4e0, 0xc0002ea000, 0xc0002bd300)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000109380, 0x161c4e0, 0xc0002ea000, 0xc0002bd300)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00046e000, 0x161cde0, 0xc00002ed40)
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2884 +0x2f4

```

**Comment by khw7096** [comment]
안녕~ 46.229.168.152 컴퓨터야~

**Comment by khw7096** [comment]
최근 handleUploadMaya 함수의 구조는 바뀌었다. 추후 비슷한 이슈가 있다면 다시 리오픈한다.
